/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AddECommerceDeclarationRequest', function() {
      beforeEach(function() {
        instance = new CarriersV2.AddECommerceDeclarationRequest();
      });

      it('should create an instance of AddECommerceDeclarationRequest', function() {
        // TODO: update the code to test AddECommerceDeclarationRequest
        expect(instance).to.be.a(CarriersV2.AddECommerceDeclarationRequest);
      });

      it('should have the property receiver (base name: "receiver")', function() {
        // TODO: update the code to test the property receiver
        expect(instance).to.have.property('receiver');
        // expect(instance.receiver).to.be(expectedValueLiteral);
      });

      it('should have the property sender (base name: "sender")', function() {
        // TODO: update the code to test the property sender
        expect(instance).to.have.property('sender');
        // expect(instance.sender).to.be(expectedValueLiteral);
      });

      it('should have the property goodsList (base name: "goodsList")', function() {
        // TODO: update the code to test the property goodsList
        expect(instance).to.have.property('goodsList');
        // expect(instance.goodsList).to.be(expectedValueLiteral);
      });

    });
  });

}));
