/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AirwaybillOperations', function() {
      beforeEach(function() {
        instance = new CarriersV2.AirwaybillOperations();
      });

      it('should create an instance of AirwaybillOperations', function() {
        // TODO: update the code to test AirwaybillOperations
        expect(instance).to.be.a(CarriersV2.AirwaybillOperations);
      });

      it('should have the property status (base name: "Status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property operations (base name: "Operations")', function() {
        // TODO: update the code to test the property operations
        expect(instance).to.have.property('operations');
        // expect(instance.operations).to.be(expectedValueLiteral);
      });

    });
  });

}));
