/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CarriersDepeshInfo', function() {
      beforeEach(function() {
        instance = new CarriersV2.CarriersDepeshInfo();
      });

      it('should create an instance of CarriersDepeshInfo', function() {
        // TODO: update the code to test CarriersDepeshInfo
        expect(instance).to.be.a(CarriersV2.CarriersDepeshInfo);
      });

      it('should have the property trackinGNO (base name: "trackinG_NO")', function() {
        // TODO: update the code to test the property trackinGNO
        expect(instance).to.have.property('trackinGNO');
        // expect(instance.trackinGNO).to.be(expectedValueLiteral);
      });

      it('should have the property weighTOFGOODS (base name: "weighT_OF_GOODS")', function() {
        // TODO: update the code to test the property weighTOFGOODS
        expect(instance).to.have.property('weighTOFGOODS');
        // expect(instance.weighTOFGOODS).to.be(expectedValueLiteral);
      });

      it('should have the property airwaybill (base name: "airwaybill")', function() {
        // TODO: update the code to test the property airwaybill
        expect(instance).to.have.property('airwaybill');
        // expect(instance.airwaybill).to.be(expectedValueLiteral);
      });

      it('should have the property depesHNUMBER (base name: "depesH_NUMBER")', function() {
        // TODO: update the code to test the property depesHNUMBER
        expect(instance).to.have.property('depesHNUMBER');
        // expect(instance.depesHNUMBER).to.be(expectedValueLiteral);
      });

      it('should have the property depesHDATE (base name: "depesH_DATE")', function() {
        // TODO: update the code to test the property depesHDATE
        expect(instance).to.have.property('depesHDATE');
        // expect(instance.depesHDATE).to.be(expectedValueLiteral);
      });

    });
  });

}));
