/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CarriersGoods', function() {
      beforeEach(function() {
        instance = new CarriersV2.CarriersGoods();
      });

      it('should create an instance of CarriersGoods', function() {
        // TODO: update the code to test CarriersGoods
        expect(instance).to.be.a(CarriersV2.CarriersGoods);
      });

      it('should have the property goodSID (base name: "goodS_ID")', function() {
        // TODO: update the code to test the property goodSID
        expect(instance).to.have.property('goodSID');
        // expect(instance.goodSID).to.be(expectedValueLiteral);
      });

      it('should have the property namEOFGOODS (base name: "namE_OF_GOODS")', function() {
        // TODO: update the code to test the property namEOFGOODS
        expect(instance).to.have.property('namEOFGOODS');
        // expect(instance.namEOFGOODS).to.be(expectedValueLiteral);
      });

    });
  });

}));
