/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CarriersEditData', function() {
      beforeEach(function() {
        instance = new CarriersV2.CarriersEditData();
      });

      it('should create an instance of CarriersEditData', function() {
        // TODO: update the code to test CarriersEditData
        expect(instance).to.be.a(CarriersV2.CarriersEditData);
      });

      it('should have the property trackinGNO (base name: "trackinG_NO")', function() {
        // TODO: update the code to test the property trackinGNO
        expect(instance).to.have.property('trackinGNO');
        // expect(instance.trackinGNO).to.be(expectedValueLiteral);
      });

      it('should have the property quantitYOFGOODS (base name: "quantitY_OF_GOODS")', function() {
        // TODO: update the code to test the property quantitYOFGOODS
        expect(instance).to.have.property('quantitYOFGOODS');
        // expect(instance.quantitYOFGOODS).to.be(expectedValueLiteral);
      });

      it('should have the property phone (base name: "phone")', function() {
        // TODO: update the code to test the property phone
        expect(instance).to.have.property('phone');
        // expect(instance.phone).to.be(expectedValueLiteral);
      });

      it('should have the property ixraCNAME (base name: "ixraC_NAME")', function() {
        // TODO: update the code to test the property ixraCNAME
        expect(instance).to.have.property('ixraCNAME');
        // expect(instance.ixraCNAME).to.be(expectedValueLiteral);
      });

      it('should have the property ixraCADRESS (base name: "ixraC_ADRESS")', function() {
        // TODO: update the code to test the property ixraCADRESS
        expect(instance).to.have.property('ixraCADRESS');
        // expect(instance.ixraCADRESS).to.be(expectedValueLiteral);
      });

      it('should have the property goodSTRAFFICFR (base name: "goodS_TRAFFIC_FR")', function() {
        // TODO: update the code to test the property goodSTRAFFICFR
        expect(instance).to.have.property('goodSTRAFFICFR');
        // expect(instance.goodSTRAFFICFR).to.be(expectedValueLiteral);
      });

      it('should have the property goodSTRAFFICTO (base name: "goodS_TRAFFIC_TO")', function() {
        // TODO: update the code to test the property goodSTRAFFICTO
        expect(instance).to.have.property('goodSTRAFFICTO');
        // expect(instance.goodSTRAFFICTO).to.be(expectedValueLiteral);
      });

      it('should have the property airwaybill (base name: "airwaybill")', function() {
        // TODO: update the code to test the property airwaybill
        expect(instance).to.have.property('airwaybill');
        // expect(instance.airwaybill).to.be(expectedValueLiteral);
      });

      it('should have the property depesHNUMBER (base name: "depesH_NUMBER")', function() {
        // TODO: update the code to test the property depesHNUMBER
        expect(instance).to.have.property('depesHNUMBER');
        // expect(instance.depesHNUMBER).to.be(expectedValueLiteral);
      });

    });
  });

}));
