/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ECommerceDeclarationGoods', function() {
      beforeEach(function() {
        instance = new CarriersV2.ECommerceDeclarationGoods();
      });

      it('should create an instance of ECommerceDeclarationGoods', function() {
        // TODO: update the code to test ECommerceDeclarationGoods
        expect(instance).to.be.a(CarriersV2.ECommerceDeclarationGoods);
      });

      it('should have the property mainGoodsGroupUnicCode (base name: "mainGoodsGroupUnicCode")', function() {
        // TODO: update the code to test the property mainGoodsGroupUnicCode
        expect(instance).to.have.property('mainGoodsGroupUnicCode');
        // expect(instance.mainGoodsGroupUnicCode).to.be(expectedValueLiteral);
      });

      it('should have the property subGoodsUnicCode (base name: "subGoodsUnicCode")', function() {
        // TODO: update the code to test the property subGoodsUnicCode
        expect(instance).to.have.property('subGoodsUnicCode');
        // expect(instance.subGoodsUnicCode).to.be(expectedValueLiteral);
      });

      it('should have the property goodsName (base name: "goodsName")', function() {
        // TODO: update the code to test the property goodsName
        expect(instance).to.have.property('goodsName');
        // expect(instance.goodsName).to.be(expectedValueLiteral);
      });

      it('should have the property quantityUnit (base name: "quantityUnit")', function() {
        // TODO: update the code to test the property quantityUnit
        expect(instance).to.have.property('quantityUnit');
        // expect(instance.quantityUnit).to.be(expectedValueLiteral);
      });

      it('should have the property quantity (base name: "quantity")', function() {
        // TODO: update the code to test the property quantity
        expect(instance).to.have.property('quantity');
        // expect(instance.quantity).to.be(expectedValueLiteral);
      });

      it('should have the property quantityFull (base name: "quantityFull")', function() {
        // TODO: update the code to test the property quantityFull
        expect(instance).to.have.property('quantityFull');
        // expect(instance.quantityFull).to.be(expectedValueLiteral);
      });

      it('should have the property currencyType (base name: "currencyType")', function() {
        // TODO: update the code to test the property currencyType
        expect(instance).to.have.property('currencyType');
        // expect(instance.currencyType).to.be(expectedValueLiteral);
      });

      it('should have the property invoicePrice (base name: "invoicePrice")', function() {
        // TODO: update the code to test the property invoicePrice
        expect(instance).to.have.property('invoicePrice');
        // expect(instance.invoicePrice).to.be(expectedValueLiteral);
      });

      it('should have the property invoicePriceFull (base name: "invoicePriceFull")', function() {
        // TODO: update the code to test the property invoicePriceFull
        expect(instance).to.have.property('invoicePriceFull');
        // expect(instance.invoicePriceFull).to.be(expectedValueLiteral);
      });

      it('should have the property invoicePriceUsd (base name: "invoicePriceUsd")', function() {
        // TODO: update the code to test the property invoicePriceUsd
        expect(instance).to.have.property('invoicePriceUsd');
        // expect(instance.invoicePriceUsd).to.be(expectedValueLiteral);
      });

      it('should have the property invoicePriceUsdNumber (base name: "invoicePriceUsdNumber")', function() {
        // TODO: update the code to test the property invoicePriceUsdNumber
        expect(instance).to.have.property('invoicePriceUsdNumber');
        // expect(instance.invoicePriceUsdNumber).to.be(expectedValueLiteral);
      });

      it('should have the property shippingCost (base name: "shippingCost")', function() {
        // TODO: update the code to test the property shippingCost
        expect(instance).to.have.property('shippingCost');
        // expect(instance.shippingCost).to.be(expectedValueLiteral);
      });

    });
  });

}));
