/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Exceptions', function() {
      beforeEach(function() {
        instance = new CarriersV2.Exceptions();
      });

      it('should create an instance of Exceptions', function() {
        // TODO: update the code to test Exceptions
        expect(instance).to.be.a(CarriersV2.Exceptions);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property code (base name: "code")', function() {
        // TODO: update the code to test the property code
        expect(instance).to.have.property('code');
        // expect(instance.code).to.be(expectedValueLiteral);
      });

      it('should have the property errorMessage (base name: "errorMessage")', function() {
        // TODO: update the code to test the property errorMessage
        expect(instance).to.have.property('errorMessage');
        // expect(instance.errorMessage).to.be(expectedValueLiteral);
      });

      it('should have the property validationError (base name: "validationError")', function() {
        // TODO: update the code to test the property validationError
        expect(instance).to.have.property('validationError');
        // expect(instance.validationError).to.be(expectedValueLiteral);
      });

      it('should have the property errorParams (base name: "errorParams")', function() {
        // TODO: update the code to test the property errorParams
        expect(instance).to.have.property('errorParams');
        // expect(instance.errorParams).to.be(expectedValueLiteral);
      });

    });
  });

}));
