/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('RequestSource', function() {
      beforeEach(function() {
        instance = CarriersV2.RequestSource;
      });

      it('should create an instance of RequestSource', function() {
        // TODO: update the code to test RequestSource
        expect(instance).to.be.a('object');
      });

      it('should have the property mobileApplication', function() {
        expect(instance).to.have.property('mobileApplication');
        expect(instance.mobileApplication).to.be("MobileApplication");
      });

      it('should have the property eCustoms', function() {
        expect(instance).to.have.property('eCustoms');
        expect(instance.eCustoms).to.be("ECustoms");
      });

      it('should have the property android', function() {
        expect(instance).to.have.property('android');
        expect(instance.android).to.be("Android");
      });

      it('should have the property ios', function() {
        expect(instance).to.have.property('ios');
        expect(instance.ios).to.be("Ios");
      });

    });
  });

}));
