/*
 * Carriers V2
 * Documentation for Carriers web apis
 *
 * OpenAPI spec version: Carriers V2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CarriersV2);
  }
}(this, function(expect, CarriersV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SearchRequest', function() {
      beforeEach(function() {
        instance = new CarriersV2.SearchRequest();
      });

      it('should create an instance of SearchRequest', function() {
        // TODO: update the code to test SearchRequest
        expect(instance).to.be.a(CarriersV2.SearchRequest);
      });

      it('should have the property dateFrom (base name: "dateFrom")', function() {
        // TODO: update the code to test the property dateFrom
        expect(instance).to.have.property('dateFrom');
        // expect(instance.dateFrom).to.be(expectedValueLiteral);
      });

      it('should have the property dateTo (base name: "dateTo")', function() {
        // TODO: update the code to test the property dateTo
        expect(instance).to.have.property('dateTo');
        // expect(instance.dateTo).to.be(expectedValueLiteral);
      });

      it('should have the property documentNumber (base name: "documentNumber")', function() {
        // TODO: update the code to test the property documentNumber
        expect(instance).to.have.property('documentNumber');
        // expect(instance.documentNumber).to.be(expectedValueLiteral);
      });

      it('should have the property trackingNumber (base name: "trackingNumber")', function() {
        // TODO: update the code to test the property trackingNumber
        expect(instance).to.have.property('trackingNumber');
        // expect(instance.trackingNumber).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property packagETYPE (base name: "packagE_TYPE")', function() {
        // TODO: update the code to test the property packagETYPE
        expect(instance).to.have.property('packagETYPE');
        // expect(instance.packagETYPE).to.be(expectedValueLiteral);
      });

    });
  });

}));
